spring.application.name=streamapp-operador

# ? JWT Config
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Hace que los queries se impriman "bonitos"
#spring.jpa.properties.hibernate.format_sql=true

# (opcional) Muestra tambi�n los valores de los par�metros
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

server.port=8081